version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elastic01
    cpus: 1
    mem_limit: 1024M
    mem_reservation: 768M
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms768m -Xmx768m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elasticnetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    container_name: kibana714
    ports:
      - 5601:5601
    networks:
      - elasticnetwork

volumes:
  elasticdata:
    driver: local

networks:
  elasticnetwork:
